import { PublicAuditSharePayload, ShareMetadata } from './types'

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function getPublicBaseUrl(): string {
  return (process.env.PUBLIC_BASE_URL || process.env.APP_BASE_URL || 'http://localhost:5000').replace(/\/$/, '')
}

function getFrontendBaseUrl(): string {
  return (process.env.FRONTEND_BASE_URL || 'http://localhost:5173').replace(/\/$/, '')
}

export function buildCanonicalShareUrl(shareId: string): string {
  return `${getPublicBaseUrl()}/share/${encodeURIComponent(shareId)}`
}

export function buildFrontendShareUrl(shareId: string): string {
  return `${getFrontendBaseUrl()}/share/${encodeURIComponent(shareId)}`
}

export function buildOgImageUrl(shareId: string): string {
  return `${getPublicBaseUrl()}/api/share/${encodeURIComponent(shareId)}/og-image.png`
}

export function buildShareMetadata(payload: PublicAuditSharePayload): ShareMetadata {
  const canonicalUrl = buildCanonicalShareUrl(payload.shareId)
  return {
    title: payload.title,
    description: payload.description,
    imageUrl: buildOgImageUrl(payload.shareId),
    canonicalUrl,
    twitterCard: 'summary_large_image'
  }
}

export function renderShareHtml(meta: ShareMetadata, payload: PublicAuditSharePayload): string {
  const safeTitle = escapeHtml(meta.title)
  const safeDescription = escapeHtml(meta.description)
  const safeCanonical = escapeHtml(meta.canonicalUrl)
  const safeImage = escapeHtml(meta.imageUrl)
  const appUrl = escapeHtml(buildFrontendShareUrl(payload.shareId))

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${safeTitle}</title>
    <meta name="description" content="${safeDescription}" />
    <link rel="canonical" href="${safeCanonical}" />

    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="AI Spend Audit" />
    <meta property="og:title" content="${safeTitle}" />
    <meta property="og:description" content="${safeDescription}" />
    <meta property="og:image" content="${safeImage}" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:url" content="${safeCanonical}" />

    <meta name="twitter:card" content="${meta.twitterCard}" />
    <meta name="twitter:title" content="${safeTitle}" />
    <meta name="twitter:description" content="${safeDescription}" />
    <meta name="twitter:image" content="${safeImage}" />

    <meta name="robots" content="index,follow,max-image-preview:large" />

    <style>
      :root { color-scheme: dark; }
      body {
        margin: 0;
        min-height: 100vh;
        font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
        background: radial-gradient(circle at 15% 20%, rgba(56, 189, 248, 0.24), transparent 30%), radial-gradient(circle at 85% 10%, rgba(99, 102, 241, 0.18), transparent 35%), #020617;
        color: #e2e8f0;
        display: grid;
        place-items: center;
      }
      .card {
        width: min(920px, calc(100% - 2rem));
        border: 1px solid rgba(148, 163, 184, 0.26);
        background: rgba(15, 23, 42, 0.8);
        border-radius: 28px;
        padding: 2rem;
        backdrop-filter: blur(16px);
        box-shadow: 0 20px 80px rgba(2, 6, 23, 0.55);
      }
      h1 {
        margin: 0;
        font-size: clamp(1.6rem, 3vw, 2.5rem);
        line-height: 1.2;
        color: #f8fafc;
      }
      p {
        margin: 1rem 0 0;
        color: #cbd5e1;
        line-height: 1.7;
      }
      a {
        display: inline-block;
        margin-top: 1.5rem;
        border-radius: 999px;
        padding: 0.8rem 1.2rem;
        text-decoration: none;
        font-weight: 600;
        color: #082f49;
        background: linear-gradient(135deg, #67e8f9, #a5b4fc);
      }
      small {
        display: block;
        margin-top: 1rem;
        color: #94a3b8;
      }
    </style>
  </head>
  <body>
    <main class="card">
      <h1>${safeTitle}</h1>
      <p>${safeDescription}</p>
      <a href="${appUrl}">Open full report</a>
      <small>Generated by AI Spend Audit</small>
    </main>
    <script>window.location.replace(${JSON.stringify(buildFrontendShareUrl(payload.shareId))});</script>
  </body>
</html>`
}
